services:

  ai-yusa:
    build: ./Ai_yusa
    container_name: legal-ai-yusa
    ports:
      - "8000:8000"  

  fastapi:
    build:
      context: ./AI_jogi
    container_name: legal-ai-jogi
    ports:
      - "8002:8002"
    env_file:
      - ./AI_jogi/.env
    restart: always